### ISSUE TITLE
detectPackageManager thinks yarn package is being used due to findWorkspaceRoot()

### ISSUE THREAD

**Issue by caschbre** [milahu/patch-package#4]
First of all, thanks for adding the [pnpm workspace support](https://github.com/ds300/patch-package/pull/302#issuecomment-1092804285) so quickly! I've been beating my head trying to patch packages in pnpm workspaces for quite a while now.

I did come across a minor issue with the package detection logic. The [following code](https://github.com/milahu/patch-package-with-pnpm-support/blob/master/src/detectPackageManager.ts#L88-L92) is causing the pnpm workspace detection to never get executed. 

```js
  } else if (yarnLockExists || findWorkspaceRoot()) {
    return "yarn"
  } else if (isFileInPnpmRoot(appRootPath, "pnpm-lock.yaml")) {
    // (fs.existsSync(join(appRootPath, "pnpm-lock.yaml"))) {
    return "pnpm"
```

What is interesting is I do not even have yarn installed on my machine.  It looks like `findWorkspaceRoot()` (from the find-yarn-workspace-root package) doesn't test if you have yarn, it just returns what it thinks is the workspace root. So that always seems to return a string if you're using workspaces, regardless of yarn being used or even installed.

I'm not sure if that needs to be changed to `yarnLockExists && findWorkspaceRoot()` or just swap the order of the `else if` blocks so that it has a chance to detect pnpm first.

I simply commented out the logic block that uses findWorkspaceRoot() and the pnpm workspace was detected.

**Comment by milahu** [comment]
could reproduce ... should be fixed in 3545f96852e6f43639998d3b94a9cc49c0c9a529
